###########################################################
# Makefile generated by xIDE for uEnergy                   
#                                                          
# Project: csr_mesh_light_csr101x
# Configuration: Release
# Generated: Thu 23. Aug 14:51:10 2018
#                                                          
# WARNING: Do not edit this file. Any changes will be lost 
#          when the project is rebuilt.                    
#                                                          
###########################################################

XIDE_PROJECT=csr_mesh_light_csr101x
XIDE_CONFIG=Release
OUTPUT=csr_mesh_light_csr101x
OUTDIR=F:/C/ArrayStorm/CSR/Software/CSRmesh-1.3-Examples-Applications_icp/applications/Arraystorm2.1 -4-5-2018/Arraystorm2.1 -12-13-2017 (modified)/applications/csr_mesh_light
DEFS=-DSERVER -DPERIPHERAL -DOBSERVER -DTHIN_CM4_MESH_NODE -DENABLE_MESH_OTA 

OUTPUT_TYPE=0
USE_FLASH=0
ERASE_NVM=1
CSFILE_CSR101x_A05=csr_mesh_light_csr101x_A05.keyr
MASTER_DB=app_gatt_db.db
LIBPATHS=..\mesh_common\mesh\libraries\csr_101x
INCPATHS=..\mesh_common\...
STRIP_SYMBOLS=0
OTAU_BOOTLOADER=1
OTAU_CSFILE=bootloader.keyr
OTAU_NAME=CSRmesh-OTA
OTAU_SECRET=00000000000000000000000000000000
OTAU_VERSION=6
OTAU_SLOT_1=0x4300
OTAU_SLOT_END=0x20000

LIBS=csrmesh light_server power_server data_server data_client 
DBS=\
\
      ../mesh_common/server/gap/gap_service_db.db\
      ../mesh_common/server/gatt/gatt_service_db.db\
      ../mesh_common/server/mesh_control/mesh_control_service_db.db\
      ../mesh_common/server/csr_ota/csr_ota_db.db\
      app_gatt_db.db

INPUTS=\
      ../mesh_common/peripheral/conn_param_update.c\
      ../mesh_common/components/nvm_manager/nvm_access.c\
      ../mesh_common/components/connection_manager/cm_common.c\
      ../mesh_common/components/connection_manager/cm_hal.c\
      ../mesh_common/components/connection_manager/cm_private.c\
      ../mesh_common/components/connection_manager/cm_security.c\
      ../mesh_common/components/connection_manager/cm_server.c\
      ../mesh_common/components/connection_manager/cm_observer.c\
      ../mesh_common/components/connection_manager/cm_peripheral.c\
      ../mesh_common/mesh/drivers/battery_hw.c\
      ../mesh_common/mesh/drivers/fast_pwm.c\
      ../mesh_common/mesh/drivers/iot_hw.c\
      ../mesh_common/mesh/drivers/csr_mesh_ps_ifce.c\
      ../mesh_common/mesh/handlers/attention_model/attention_model_handler.c\
      ../mesh_common/mesh/handlers/battery_model/battery_model_handler.c\
      ../mesh_common/mesh/handlers/core_mesh/core_mesh_handler.c\
      ../mesh_common/mesh/handlers/data_model/data_model_handler.c\
      ../mesh_common/mesh/handlers/light_model/light_model_handler.c\
      ../mesh_common/mesh/handlers/power_model/power_model_handler.c\
      ../mesh_common/mesh/handlers/common/app_util.c\
      ../mesh_common/mesh/handlers/connection/connection_handler.c\
      ../mesh_common/mesh/handlers/advertisement/advertisement_handler.c\
      ../mesh_common/mesh/handlers/time_model/time_model_handler.c\
      ../mesh_common/mesh/handlers/action_model/action_model_handler.c\
      ../mesh_common/mesh/handlers/largeobjecttransfer_model/largeobjecttransfer_model_handler.c\
      ../mesh_common/mesh/handlers/asset_model/asset_model_handler.c\
      ../mesh_common/mesh/handlers/tracker_model/tracker_model_handler.c\
      ../mesh_common/server/gap/gap_service.c\
      ../mesh_common/server/gatt/gatt_service.c\
      ../mesh_common/server/mesh_control/mesh_control_service.c\
      ../mesh_common/server/csr_ota/csr_ota_service.c\
      main_app.c\
      app_mesh_handler.c\
      app_hw.c\
      byte_queue.c\
      $(DBS)

KEYR=\
      csr_mesh_light_csr101x_A05.keyr\
      bootloader.keyr


-include csr_mesh_light_csr101x.mak
include $(SDK)/genmakefile.uenergy
